CREATE TABLE IF NOT EXISTS ADMINISTRATOR (ID INT NOT NULL AUTO_INCREMENT, USERNAME VARCHAR(25) UNIQUE NOT NULL, PASSWORD VARCHAR(25) NOT NULL, PRIMARY KEY(ID));


INSERT INTO ADMINISTRATOR VALUES('AUMA', 'auma');
INSERT INTO ADMINISTRATOR VALUES('AGMA', 'agma');
INSERT INTO ADMINISTRATOR VALUES('VIVA', 'viva');
INSERT INTO ADMINISTRATOR VALUES('BIDR', 'bidr');
INSERT INTO ADMINISTRATOR VALUES('AUTV', 'autv');

CREATE TABLE IF NOT EXISTS ITEM 
(ID INT NOT NULL AUTO_INCREMENT,
SKU VARCHAR(50) UNIQUE NOT NULL,
NAME VARCHAR(50) NOT NULL,
PRICE INT,
SUMMARY VARCHAR(256),
PHOTO VARCHAR(256),
CATEGORY VARCHAR(50),
PRIMARY KEY(ID));

CREATE TABLE IF NOT EXISTS PURCHASE_HISTORY
(ID INT NOT NULL AUTO_INCREMENT,
STATUS VARCHAR(25) NOT NULL,
PURCHASE_DATE DATE NOT NULL,
PRIMARY KEY(ID));

CREATE TABLE IF NOT EXISTS PURCHASED_ITEMS
(PURCHASE_ID INT NOT NULL,
ITEM_ID INT NOT NULL,
AMOUNT INT NOT NULL,
PRIMARY KEY (PURCHASE_ID, ITEM_ID),
FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASE_HISTORY (ID),
FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID)
);

CREATE TABLE IF NOT EXISTS BUYER_ADDRESS
(
ID INT NOT NULL AUTO_INCREMENT,
COUNTRY VARCHAR(25),
CITY VARCHAR(25),
STREET VARCHAR(25),
HOUSE VARCHAR(4),
FLAT INT,
POSTCODE INT,
PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS BUYER
(
ID INT NOT NULL AUTO_INCREMENT,
EMAIL VARCHAR(50) UNIQUE NOT NULL,
NAME VARCHAR(25),
SURNAME VARCHAR(25),
PASSWORD VARCHAR(25),
ADDRESS_ID INT,
PHONE_NUMBER INT,
IS_BLOCKED BOOLEAN,
PRIMARY KEY (ID),
FOREIGN KEY (ADDRESS_ID) REFERENCES BUYER_ADDRESS(ID)
);

CREATE TABLE IF NOT EXISTS CART
(
BUYER_ID INT NOT NULL,
ITEM_ID INT NOT NULL,
AMOUNT INT,
PRIMARY KEY (BUYER_ID, ITEM_ID),
FOREIGN KEY (BUYER_ID) REFERENCES BUYER (ID),
FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID)
);